theme: jekyll-theme-midnight
title: Sujith M S
description: Lab No. 5, Mendeleev, Fourth year BS MS student, Indian Institute of Science Education and Research (IISER), Pune, Dr. Homi Bhabha Road, Pashan, Pune, Maharashtra, INDIA - 411008	
github: 
is_project_page: false
